version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: proofmeet-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - proofmeet-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proofmeet-backend
    env_file:
      - .env
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - proofmeet-network
    command: npm run dev

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proofmeet-frontend
    env_file:
      - .env
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - proofmeet-network
    command: npm run dev

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: proofmeet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proofmeet-network

volumes:
  postgres_data:
  redis_data:

networks:
  proofmeet-network:
    driver: bridge
