name: Daily Railway Redeploy

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  trigger-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create redeploy trigger
        run: |
          date > .railway-deploy-trigger
          git add .railway-deploy-trigger
          git commit -m "Automated daily redeploy - $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        run: |
          git push origin main

      - name: Trigger Railway webhook (if configured)
        if: secrets.RAILWAY_WEBHOOK_URL != ''
        run: |
          curl -X POST ${{ secrets.RAILWAY_WEBHOOK_URL }}

